# Generated by Django 2.0.5 on 2018-08-06 10:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_auto_20180806_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverfyrecord',
            name='add_time',
        ),
        migrations.AlterField(
            model_name='emailverfyrecord',
            name='send_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailverfyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10,
                                   verbose_name='验证码类型'),
        ),
    ]
