# Generated by Django 2.0.5 on 2018-08-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0006_auto_20180806_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/banner/%Y/%M', verbose_name='轮播图'),
        ),
    ]
