# Generated by Django 2.0.5 on 2018-06-28 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20180628_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
